server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      # 开启从注册中心动态创建路由的功能
      discovery:
        locator:
          enabled: true

      # 断言路由转发yml配置推荐使用，对应的还有编码配置
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          # predicates就是为了实现一组匹配规则，让请求过来找到对应的route进行处理
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            #- After=2020-07-12T01:09:05.408+08:00[Asia/Shanghai]
            #- Before=2020-07-12T01:09:05.408+08:00[Asia/Shanghai]
            #- Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] ,  2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
            #- Cookie=username,ydz  # curl http://localhost:9527/payment/lb --cookie "username=ydz"
            #- Header=X-Request-Id, \d+
            #请求头中要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb -H "X-Request-Id:123"


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka